apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: REGISTRY_HOSTNAME/sparkdev2019/IMAGE:GITHUB_SHA
          ports:
            - containerPort: 8080
        - name: mongo
          image: mongo
          imagePullPolicy: "Always"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
            name: mongodb
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "web-app-hpa"
  namespace: "default"
  labels:
    app: "web-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "web-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
